### ISSUE TITLE
How to finetune?

### ISSUE THREAD

**Issue by sicko-mode-df** [Howuhh/cic_gym#1]
Hello, I'm sorry to bother you. How can I find finetune? Use an algorithm similar to DQN to select skills?

**Comment by Howuhh** [comment]
Hi @sicko-mode-df! For example on finetuning as it was done in the paper, I suggest you look at the original code here:
https://github.com/rll-research/cic/blob/master/finetune.py

I didn't try it tho, because for my tasks I only needed the pre-training.
